export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';
export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING';
export const CLEAR_PRODUCT_API_STATE = 'CLEAR_PRODUCT_API_STATE';

export const ADD_FILTER_DATA = 'ADD_FILTER_DATA';
